config/routes.rb
Minotaur::Application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root to: 'activation_codes#index'

  resources :activation_codes, only: [:index] do
    get :validate, on: :member
  end

  resources :patient_enrollments, only: [:new] do
    post :register, on: :member
  end

  resource :patient_management, controller: :patient_management, only: [] do
    get :index, to: :select_study_and_site
    post :invite
    get :available_subjects
  end

  resources :study_sites, only: [:index]

  get :logout, controller: :application

  get '*path', controller: :application, to: :routing_error
end

app/models/patient_enrollment.rb
class PatientEnrollment
  include ActiveModel::Model
  attr_accessor :uuid, :login, :password, :security_question, :answer, :activation_code, :login_confirmation,
                :tou_dpn_agreement, :initials, :email, :enrollment_type, :study_uuid, :study_site_uuid,
                :subject_id, :state, :tou_accepted_at, :created_at
  RIGHT_TO_LEFT_LANGUAGE_CODES = ['ara', 'heb']

  def self.by_study_and_study_site(options)
    raise ArgumentError.new('Argument must be a hash.') unless options.is_a?(Hash)
    [:study_uuid, :study_site_uuid, :user_uuid].each do |key|
      raise ArgumentError.new("Required argument #{key} is blank.") if options[key].blank?
    end

    response = Euresource::PatientEnrollments.get(:all, params: options.slice(:study_uuid, :study_site_uuid),
      http_headers: { 'X-MWS-Impersonate' => options[:user_uuid] })

    if response.last_response.status == 200
      JSON.parse(response.last_response.body).map{ |pe_hash| PatientEnrollment.new(pe_hash) }
    else
      raise EuresourceError.new(response.last_response.body)
    end

  rescue => e
    Rails.logger.error_with_data("Error retrieving patient enrollments: #{e.message}", options)
    raise
  end

  def tou_dpn_agreement_body
    Nokogiri::HTML(tou_dpn_agreement['html']).css('body').to_s.html_safe
  end

  # Language code is either assigned or retrieved from the TOU/DPN.
  # TODO: Can we drop the TOU/DPN retrieval? It should always match the TOU/DPN.
  #
  def language_code
    @language_code || tou_dpn_agreement['language_code']
  end

  def language_code=(value)
    @language_code = value
  end

  def tou_dpn_agreement
    @tou_dpn_agreement ||= remote_tou_dpn_agreement
  end

  def script_direction
    RIGHT_TO_LEFT_LANGUAGE_CODES.include?(language_code) ? 'rtl' : 'ltr'
  end
  
  # stars out emails and formats dates for provider grid display
  def grid_formatted
    { created_at: self.created_at.blank? ? '' : self.formatted_date,
      subject_id: self.subject_id,
      email: self.email.blank? ? '' : self.anonymized_email,
      initials: self.initials,
      activation_code: self.activation_code,
      state: self.state.blank? ? '' : self.state.capitalize }
  end
  
  # anonymizes emails and caps their length if they are long
  def anonymized_email
    unless self.email.blank?
      user, domain = self.email.split("@")
      user, domain, tld = if domain.present?
        domain = domain.split('.')
        [user.chars, domain.first.chars, domain.from(1).join('.')]
      else
        [user.chars, ''.chars, '']
      end
      
      if user.length >= 2
        user = user.take(2).join << '*' * (user.length > 20 ? 18 : user.length - 2)
      else
        user = user.take(2).join << '***'
      end
      
      if domain.length >= 2
        domain = domain.take(2).join << '*' * (domain.length > 10 ? 8 : domain.length - 2)
      else
        domain = domain.take(2).join << '***'
      end
      
      "#{user}@#{domain}.#{tld}"
    else
      ''
    end
  end
  
  # formats date for display in the patient management grid
  def formatted_date
    Date.strptime(self.created_at).strftime('%d-%^b-%Y')
  end

  private
  # Returns the body of the remote tou dpn agreement.
  # raises an error if there is no uuid present
  #
  def remote_tou_dpn_agreement
    validate_presence_of_attribute!(:uuid, 'Cannot request TOU/DPN agreement without attribute:')
    response = Euresource::PatientEnrollment.invoke(:tou_dpn_agreement, {uuid: uuid})
    response_body_or_raise!(response)
  end

  # Takes a attribute argument and validates the attribute as being present or raises an error.
  #
  def validate_presence_of_attribute!(attribute, message = 'Presence validation failed for attribute:')
    unless self.send(attribute).present?
      raise PatientEnrollmentError.new("#{message} #{attribute}")
    end
  end

  # Takes a response object argument.
  #   If response is successful, returns body of the response object
  #   otherwise raises an error with the response status and body.
  #
  def response_body_or_raise!(response)
   if response.status == 200
      JSON.parse(response.body)
    else
      raise RemotePatientEnrollmentError.new("Received unexpected response for tou_dpn_agreement. " <<
        "Response status: #{response.status}. Response body: #{response.body}")
    end
  end
  
  class PatientEnrollmentError < StandardError; end
  class RemotePatientEnrollmentError < StandardError; end
end

app/controllers/patient_enrollments_controller.rb
class PatientEnrollmentsController < ApplicationController
  layout "patient_registration"

  def new
    @patient_enrollment_uuid = session[:patient_enrollment_uuid]
    @patient_enrollment = PatientEnrollment.new(uuid: @patient_enrollment_uuid)
    @tou_dpn_agreement_body = @patient_enrollment.tou_dpn_agreement_body
    @script_direction = @patient_enrollment.script_direction
    @security_questions = SecurityQuestions.find(@patient_enrollment.language_code || I18n.default_locale).map { |sq|  [sq[:name], sq[:id]]}
  rescue StandardError => e
    # TODO: render error modal
    return render json: {message: "Unable to continue with registration. Error: #{e.message}"}, status: 422
  end

  def register
    unless session[:patient_enrollment_uuid] && session[:activation_code]
      redirect_to activation_codes_path and return
    end

    register_response = Euresource::PatientEnrollments.invoke(
      :register,
      {uuid: session[:patient_enrollment_uuid]},
      {patient_enrollment: clean_registration_params})

    if register_response.status == 200
      render 'download'
      reset_session
    else
      render json: {errors: "Unable to complete registration: #{register_response.body}"}, status: register_response.status
    end
  end

  private

  # Returns cleaned registration params or responds 422 per strong parameters.
  #   Example: {login: 'cdr-adama@gmail.com', password: 'ejolmos', activation_code: 'HX6PKN', tou_accepted_at: ... }
  #
  def clean_registration_params
    params.require(:patient_enrollment)
    patient_enrollment_params = params['patient_enrollment']
    required_register_params.each { |p| patient_enrollment_params.require(p) }

    replace_security_question_key(patient_enrollment_params)

    if new_user_params.any? {|p| patient_enrollment_params.include?(p) }
      new_user_params.each { |p| patient_enrollment_params.require(p) }
    end

    patient_enrollment_params.permit(all_register_params)
      .merge(activation_code: session[:activation_code], tou_accepted_at: Time.now.to_s)
  end

  # Replaces 'security_question' with 'security_question_id'
  #
  def replace_security_question_key(params)
    unless params['security_question_id'].present?
      if security_question_id = params.delete('security_question')
        params['security_question_id'] = security_question_id
      end
    end
  end

  def all_register_params
    required_register_params + new_user_params
  end

  def required_register_params
    ['login', 'password']
  end

  def new_user_params
    ['security_question_id', 'answer']
  end
end

app/views/patient_enrollments/_email_form.html.haml
%h3.form-header
  = t("registration.email_form.email_label")
%p.form_instruction
  = t("registration.email_form.form_instruction")

= fields_for @patient_enrollment do |f|
  .form-group
    = f.label :login, t("registration.email_form.email_label")
    = f.email_field :login, class: 'registration-input form-control'
  .form-group
    = f.label :login_confirmation, t("registration.email_form.reenter_label")
    = f.email_field :login_confirmation, class: 'registration-input form-control'
.validation_error

%a.btn.btn-primary.btn-block#next-email(href="#registration-details" role="button")=t("application.btn_next")

app/views/patient_enrollments/_landing_page.html.haml
%h3.form-header
  =t("registration.form_heading")
%p.form-instruction
  =t("registration.welcome.welcome_message")
.row
  .col-xs-2
    =image_tag 'register.png', id: 'register'
  .col-xs-8
    %p=t("registration.welcome.register_1")
    %p=t("registration.welcome.register_2")
.row
  .col-xs-2
    =image_tag 'download.png', id: 'download'
  .col-xs-8
    %p
    %p= t("registration.welcome.download")
.row
  .col-xs-2
    =image_tag 'login_green.png', id: 'login'
  .col-xs-8
    %p=t("registration.welcome.login")

%a.btn.btn-primary.btn-block#next-landing(href="#registration-details" role="button")=t("application.btn_next")

app/views/patient_enrollments/_password_form.html.haml
%h3.form-header= t("registration.password_form.password_label")
= t("registration.password_form.form_instruction_1")
%strong= t("registration.password_form.form_instruction_1_bold")
= t("registration.password_form.form_instruction_1_2")

%ul.password-instructions
  %li= t("registration.password_form.ul_1")
  %li= t("registration.password_form.ul_2")
  %li= t("registration.password_form.ul_3")
  %li= t("registration.password_form.ul_4")

%br
= fields_for @patient_enrollment do |f|
  .form-group
    = f.label :password, t("registration.password_form.password_label")
    = f.password_field :password, class: 'registration-input form-control'
  .form-group
    = f.label :password_confirmation, t("registration.password_form.reenter_label")
    = f.password_field :password_confirmation, class: 'registration-input form-control'
.validation_error
%a.btn.btn-primary.btn-block#next-password(href="#registration-details" role="button")=t("application.btn_next")

app/views/patient_enrollments/_security_question_form.html.haml
%h3.form-header=t("registration.security_question_form.dropdown_placeholder")
.form_instruction
  = t("registration.security_question_form.form_instruction")
  %strong= t("registration.security_question_form.form_instruction_bold")
= fields_for @patient_enrollment do |f|
  / label is included so capybara can find the control, but not displayed on the page.  Not localizing because not displayed
  .form-group
    = f.label :security_question, 'Security Question', id: "question-label", class: 'invisible'
    = f.select :security_question, @security_questions, {include_blank:  t("registration.security_question_form.dropdown_placeholder")}, {class: 'form-control'}
  .form-group
    = f.label :answer, t("registration.security_question_form.answer_label")
    = f.text_field :answer, class: 'registration-input form-control', placeholder: t("registration.security_question_form.answer_placeholder"), autocomplete: 'off'

  %input.btn.btn-primary.btn-block.disabled#create-account{ type: 'submit', value: t("registration.security_question_form.btn_create")}

app/views/patient_enrollments/_tou_dpn_agreement.html.haml
%h3.form-header=t("registration.terms_of_use.tou_header")
- if @tou_dpn_agreement_body.present?
  .tou_dpn_agreement{style: "direction: #{@script_direction}"}= @tou_dpn_agreement_body
%a.btn.btn-primary.btn-block#next-agree(href="#registration-details" role="button")=t("application.btn_agree")

app/views/patient_enrollments/download.html.haml
- content_for :page_body do
  .patient-enrollment
    .header
      =image_tag 'Medidata_Logo_white_RGB_2.png'

    %p#download-instruction= t("download.header")
    #progress-graphic
      .progress-item.register
        =image_tag 'register.png'
        .caption Register
      .gray-line
      .progress-item.download
        =image_tag 'download.png'
        .caption Download
      .gray-line
      .progress-item.login
        =image_tag 'login.png'
        .caption Login
    #download-links
      %a.download-android
        =image_tag 'app_badge_google.png', class: 'badge-img', id: 'android-badge'
        %span.sr-only='Download for Android'
      %a.download-ios(href='https://itunes.apple.com/app/patient-cloud/id554170114?mt=8')
        =image_tag 'app_badge_ios.png', class: 'badge-img', id: 'ios-badge'
        %span.sr-only='Download for iOS'
    #login-screen-img
      =image_tag 'phone.png'

app/views/patient_enrollments/new.html.haml
- content_for :page_body do
  .patient-enrollment
    .header
      =image_tag 'Medidata_Logo_white_RGB_2.png'
      %a.back-arrow.pull-left.hidden
        %i.fa.fa-angle-left
        %span.sr-only='Back'

    .progress-indicator.hidden
      .step.default
        %span.sr-only='Page 1 of 4'
      .step.incomplete
        %span.sr-only='Page 2 of 4'
      .step.incomplete
        %span.sr-only='Page 3 of 4'
      .step.incomplete
        %span.sr-only='Page 4 of 4'

    = form_tag register_patient_enrollment_path(@patient_enrollment_uuid), id: 'reg-form', remote: @in_app_browser ? true : false
    
    #registration-details.clearfix
      .item.active#landing_page
        = render 'landing_page'
      .item#tou_dpn_agreement
        = render 'tou_dpn_agreement'
      .item#email
        = render 'email_form'
      .item#password
        = render 'password_form'
      .item#security_question
        = render 'security_question_form'